<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1mH4UVM\srcApp_KernelProdDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1mH4UVM/srcApp_KernelProdDebugContainer.php') {
    touch(__DIR__.'/Container1mH4UVM.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdDebugContainer::class, false)) {
    \class_alias(\Container1mH4UVM\srcApp_KernelProdDebugContainer::class, srcApp_KernelProdDebugContainer::class, false);
}

return new \Container1mH4UVM\srcApp_KernelProdDebugContainer([
    'container.build_hash' => '1mH4UVM',
    'container.build_id' => '5dff8fbb',
    'container.build_time' => 1573251178,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1mH4UVM');
