<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVAGxZhl\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVAGxZhl/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerVAGxZhl.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerVAGxZhl\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerVAGxZhl\srcApp_KernelProdContainer([
    'container.build_hash' => 'VAGxZhl',
    'container.build_id' => 'f0a97306',
    'container.build_time' => 1573251145,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVAGxZhl');
