<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.YIUCPlB' shared service.

return $this->privates['.service_locator.YIUCPlB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'ad' => ['privates', '.errored..service_locator.YIUCPlB.App\\Entity\\Ad', NULL, 'Cannot autowire service ".service_locator.YIUCPlB": it references class "App\\Entity\\Ad" but no such service exists.'],
    'repo' => ['privates', 'App\\Repository\\AdRepository', 'getAdRepositoryService.php', true],
], [
    'ad' => 'App\\Entity\\Ad',
    'repo' => 'App\\Repository\\AdRepository',
]);
