<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHm2TRzi\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHm2TRzi/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHm2TRzi.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHm2TRzi\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHm2TRzi\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Hm2TRzi',
    'container.build_id' => '3b60c86c',
    'container.build_time' => 1574158256,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHm2TRzi');
