<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZYxnIND\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZYxnIND/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZYxnIND.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZYxnIND\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZYxnIND\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZYxnIND',
    'container.build_id' => '82d8ad43',
    'container.build_time' => 1574169938,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZYxnIND');
