<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKWBUTem\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKWBUTem/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKWBUTem.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKWBUTem\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKWBUTem\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KWBUTem',
    'container.build_id' => '05b4a29a',
    'container.build_time' => 1574112172,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKWBUTem');
